<?php
namespace Turbopress;

if (!defined('ABSPATH')) {
    exit;
}

/**
 * 13-point self-diagnostic. Results are stored in the 'turbopress_health'
 * option (drives the admin checklist UI), and pushed daily to the SaaS
 * control plane via the heartbeat route so fleet health is visible remotely.
 */
class HealthCheck {
    private const OPTION_KEY = 'turbopress_health';
    private const THROTTLE = 900; // 15 minutes

    private Config $config;
    private ApiClient $api_client;

    public function __construct(Config $config, ApiClient $api_client) {
        $this->config = $config;
        $this->api_client = $api_client;
    }

    /** Lazy run on admin page views, throttled. */
    public function maybe_run(): void {
        $stored = get_option(self::OPTION_KEY, []);
        $last = is_array($stored) ? (int) ($stored['checked_at'] ?? 0) : 0;
        if ((time() - $last) < self::THROTTLE) {
            return;
        }
        $this->run();
    }

    public function run(): array {
        $host = strtolower((string) parse_url(home_url(), PHP_URL_HOST));
        $css_glob = TURBOPRESS_CACHE_DIR . '/' . md5($host) . '/css/*.css';
        $css_files = glob($css_glob) ?: [];

        $foreign = CacheIntegration::detect_foreign_dropin();

        // Loopback self-test: does our own cache serve a HIT, and is the
        // served HTML carrying the CURRENT plugin version fingerprint?
        // Cached for the report's lifetime to avoid a request storm.
        $loopback = get_transient('turbopress_health_loopback');
        if (!is_array($loopback)) {
            $loopback = $this->probe_loopback();
            set_transient('turbopress_health_loopback', $loopback, self::THROTTLE);
        }
        $loopback_hit = (bool) ($loopback['hit'] ?? false);
        $served_version = isset($loopback['version']) ? (string) $loopback['version'] : null;

        // Edge reachability (cached — a slow/failed probe shouldn't stall admin).
        $edge = get_transient('turbopress_health_edge');
        if ($edge === false) {
            $edge = $this->config->is_connected() ? $this->probe_edge() : null;
            if ($edge !== null) {
                set_transient('turbopress_health_edge', $edge, self::THROTTLE);
            }
        }

        $checks = [
            [
                'key' => 'dropin_installed',
                'label' => 'Turbopress drop-in installed',
                'status' => CacheIntegration::is_our_dropin_installed() ? 'ok' : ($foreign !== null ? 'info' : 'warning'),
                'detail' => CacheIntegration::is_our_dropin_installed()
                    ? 'advanced-cache.php is ours'
                    : ($foreign !== null
                        ? 'Delegated to ' . $foreign['label'] . ' (it owns the single drop-in slot; Turbopress hooks its purge events)'
                        : 'advanced-cache.php is not installed'),
            ],
            [
                'key' => 'wp_cache_constant',
                'label' => 'WP_CACHE constant enabled',
                'status' => (defined('WP_CACHE') && WP_CACHE) ? 'ok' : ($foreign !== null ? 'info' : 'warning'),
                'detail' => (defined('WP_CACHE') && WP_CACHE)
                    ? 'true'
                    : ($foreign !== null ? 'Delegated to ' . $foreign['label'] : 'not defined/false'),
            ],
            [
                'key' => 'foreign_cache_conflict',
                'label' => 'Page-cache conflict',
                'status' => $foreign === null ? 'ok' : 'ok',
                'detail' => $foreign === null
                    ? 'No foreign advanced-cache.php'
                    : 'Coexisting with ' . $foreign['label'] . ' — Turbopress purges it automatically on content changes',
            ],
            [
                'key' => 'loopback_cache_hit',
                'label' => 'Page cache serving (loopback test)',
                'status' => $loopback_hit ? 'ok' : ($foreign !== null ? 'info' : 'warning'),
                'detail' => $loopback_hit
                    ? 'X-Turbopress-Cache: HIT observed'
                    : ($foreign !== null
                        ? 'Host cache (' . $foreign['label'] . ') is serving pages — expected when it owns the drop-in'
                        : 'No cache HIT on loopback request'),
            ],
            [
                'key' => 'served_html_current',
                'label' => 'Served HTML is current',
                'status' => $served_version === null ? 'warning' : ($served_version === TURBOPRESS_VERSION ? 'ok' : 'error'),
                'detail' => $served_version === null
                    ? 'No Turbopress fingerprint on served homepage (host cache serving unoptimized HTML, or DOM engine inactive)'
                    : ($served_version === TURBOPRESS_VERSION
                        ? 'data-tp-version matches ' . TURBOPRESS_VERSION
                        : 'STALE: homepage served by a host/foreign cache was generated by v' . $served_version . ' — purge the host cache (LiteSpeed etc.)'),
            ],
            [
                'key' => 'cache_dir_writable',
                'label' => 'Cache directory writable',
                'status' => wp_is_writable(TURBOPRESS_PAGES_DIR) ? 'ok' : 'error',
                'detail' => TURBOPRESS_PAGES_DIR,
            ],
            [
                'key' => 'compression_available',
                'label' => 'Pre-compression available',
                'status' => function_exists('gzencode') ? 'ok' : 'warning',
                'detail' => function_exists('gzencode')
                    ? (function_exists('brotli_compress') ? 'gzip + brotli' : 'gzip only')
                    : 'none',
            ],
            [
                'key' => 'wp_cron_enabled',
                'label' => 'WP-Cron enabled',
                'status' => !defined('DISABLE_WP_CRON') || !DISABLE_WP_CRON ? 'ok' : 'warning',
                'detail' => defined('DISABLE_WP_CRON') && DISABLE_WP_CRON
                    ? 'DISABLE_WP_CRON is set — edge dispatch relies on push callbacks only'
                    : 'Default scheduler active',
            ],
            [
                'key' => 'edge_api_reachable',
                'label' => 'Edge API reachable',
                'status' => $edge === null ? 'warning' : ($edge ? 'ok' : 'error'),
                'detail' => $edge === null ? 'Not connected' : ($edge ? 'verify ok' : 'verify failed'),
            ],
            [
                'key' => 'critical_css_generated',
                'label' => 'Critical CSS generated',
                'status' => !empty($css_files) ? 'ok' : 'warning',
                'detail' => count($css_files) . ' file(s) cached',
            ],
            [
                'key' => 'callback_secret_configured',
                'label' => 'Callback secret configured',
                'status' => strlen(Config::get_callback_secret_static()) >= 32 ? 'ok' : 'error',
                'detail' => 'HMAC push verification',
            ],
            [
                'key' => 'plugin_version_current',
                'label' => 'Plugin version current',
                'status' => get_option('turbopress_version') === TURBOPRESS_VERSION ? 'ok' : 'warning',
                'detail' => TURBOPRESS_VERSION,
            ],
            [
                'key' => 'output_buffering_active',
                'label' => 'DOM engine active',
                'status' => (bool) $this->config->get('caching.enabled', true) || (bool) $this->config->get('critical_css.enabled', true) ? 'ok' : 'warning',
                'detail' => 'Critical CSS / deferral pipeline',
            ],
            [
                'key' => 'htaccess_optimized',
                'label' => '.htaccess asset rules',
                'status' => Htaccess_Manager::is_active() ? 'ok' : 'info',
                'detail' => Htaccess_Manager::is_active()
                    ? 'Immutable/30d TTLs + pre-compressed serving active'
                    : ('reason: ' . (Htaccess_Manager::get_state()['reason'] ?? 'not installed') . ' — long-cache TTLs unavailable on this host'),
            ],
        ];

        $report = [
            'checked_at' => time(),
            'checks' => $checks,
        ];

        // Surface auto-degrade activity to the SaaS attention queue (E2).
        $degrade = get_option(AutoDegrade::OPTION, []);
        if (is_array($degrade) && !empty($degrade['at'])) {
            $report['auto_degrade'] = [
                'at' => (int) $degrade['at'],
                'from' => (string) ($degrade['from'] ?? ''),
                'to' => (string) ($degrade['to'] ?? ''),
                'rate' => $degrade['rate'] ?? null,
                'views' => (int) ($degrade['views'] ?? 0),
            ];
        }

        update_option(self::OPTION_KEY, $report);

        return $report;
    }

    /**
     * Loopback probe: is our cache serving, and which plugin version
     * generated the served HTML (data-tp-version fingerprint)?
     */
    private function probe_loopback(): array {
        $response = wp_remote_get(home_url('/'), [
            'timeout' => 10,
            'headers' => ['Cache-Control' => 'no-cache'],
        ]);
        if (is_wp_error($response)) {
            return ['hit' => false, 'version' => null];
        }

        $header = (string) wp_remote_retrieve_header($response, 'x-turbopress-cache');
        $body = (string) wp_remote_retrieve_body($response);

        $version = null;
        if (preg_match('/<html\b[^>]*\sdata-tp-version=["\']([0-9.]+)["\']/i', substr($body, 0, 4096), $m)) {
            $version = $m[1];
        }

        return [
            'hit' => stripos($header, 'HIT') !== false,
            'version' => $version,
        ];
    }

    private function probe_edge(): bool {
        $result = $this->api_client->verify_connection();
        return !is_wp_error($result) && !empty($result['success']);
    }

    /**
     * Push the latest report to the SaaS control plane (daily cron).
     * Also carries the current deployment status so the dashboard can push
     * Deploy/Test commands back through the heartbeat response.
     */
    public function push_to_edge(): void {
        if (!$this->config->is_connected()) {
            return;
        }

        $report = get_option(self::OPTION_KEY, []);
        if (!is_array($report) || empty($report['checked_at'])) {
            return;
        }

        $report['deployment'] = ['status' => $this->config->get('deployment.status', 'live')];

        $result = $this->api_client->send_heartbeat($report);
        if (!empty($result['success'])) {
            $apply = $result['data']['apply'] ?? null;
            if (is_array($apply['deployment'] ?? null)) {
                ApiClient::apply_remote_deployment($this->config, $apply);
            }
        }
    }

    public static function get_latest(): array {
        $report = get_option(self::OPTION_KEY, []);
        return is_array($report) ? $report : [];
    }
}
