<?php
namespace WPInstant;

if (!defined('ABSPATH')) {
    exit;
}

class Plugin {
    private static ?Plugin $instance = null;
    public Config $config;
    public ApiClient $api_client;
    public CacheManager $cache_manager;
    public CachePurger $cache_purger;
    public DomEngine $dom_engine;
    public NonceRefresher $nonce_refresher;
    public CartFragment $cart_fragment;
    public PresetEngine $preset_engine;
    public CacheIntegration $cache_integration;
    public HealthCheck $health_check;
    public Updater $updater;
    public BloatRemover $bloat_remover;
    public AutoPurge $auto_purge;

    public static function get_instance(): Plugin {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        $this->config = new Config();
        $this->api_client = new ApiClient($this->config);
        $this->cache_manager = new CacheManager($this->config);
        $this->cache_purger = new CachePurger($this->cache_manager);
        $this->dom_engine = new DomEngine($this->config, $this->api_client);
        $this->nonce_refresher = new NonceRefresher();
        $this->cart_fragment = new CartFragment($this->config);
        $this->preset_engine = new PresetEngine($this->config);
        $this->cache_integration = new CacheIntegration();
        $this->health_check = new HealthCheck($this->config, $this->api_client);
        $this->updater = new Updater($this->config);
        $this->bloat_remover = new BloatRemover($this->config);
        $this->auto_purge = new AutoPurge($this->config);
    }

    public function init(): void {
        // Upgrade housekeeping: when the plugin version changes, purge the
        // static page cache so HTML transformed by an older release (e.g.
        // with the broken script-delaying logic) is never served stale.
        $installed_version = get_option('wp_instant_version', '');
        if ($installed_version !== WP_INSTANT_VERSION) {
            update_option('wp_instant_version', WP_INSTANT_VERSION);
            CacheManager::purge_all_static();
            // Propagate to host/foreign caches (LiteSpeed etc.): without this,
            // HTML transformed by the OLD release stays served indefinitely.
            CacheIntegration::purge_foreign_caches('all');
            // Re-assert our drop-in on upgrades (source file may have changed).
            CacheIntegration::install_dropin();
            // Install/refresh .htaccess delivery rules (markers replace cleanly).
            Htaccess_Manager::install();
            // Drop critical CSS generated by the previous release: extractor
            // output shape changes between versions (e.g. v1.7.0 pseudo-
            // element repairs) and stale files keep serving via the
            // per-URL cache lookups until the edge pushes fresh CSS.
            $host_hash = md5(wp_parse_url(home_url(), PHP_URL_HOST) ?: '');
            $css_dir = WP_INSTANT_CACHE_DIR . '/' . $host_hash . '/css';
            if (is_dir($css_dir)) {
                foreach (glob($css_dir . '/*.css') ?: [] as $file) {
                    @unlink($file);
                }
            }
            // v1.11.0: LCP URLs measured pre-extraction-bypass pointed at the
            // optimized page (possibly worker-rewritten); re-measure fresh.
            delete_option('wp_instant_lcp_images');
        }

        // Initialize Cache Purger hooks
        $this->cache_purger->init();

        // D4: extend nonce lifetime to the cache TTL on every
        // visitor-facing request (generation and verification stay
        // consistent — cached pages keep working even when the hydrator
        // can't run, e.g. JS disabled).
        //
        // CRITICAL: the extension must NOT cover core REST/AJAX traffic.
        // is_admin() is false for /wp-json/, so the filter otherwise alters
        // the nonce tick during REST verification: nonces minted in
        // wp-admin (default tick) then fail hash-equality in REST and every
        // editor save (POST /wp-json/wp/v2/pages/<id>) returns 403.
        // Our own /wp-instant/v1/ namespace keeps the extension — its
        // endpoints mint nonces for FRONTEND verification.
        if (!is_admin() && !$this->is_core_rest_or_ajax()) {
            $nonce_ttl = max(DAY_IN_SECONDS, (int) $this->config->get('caching.ttl', 604800));
            add_filter('nonce_life', static fn(int $life): int => max($life, $nonce_ttl));
        }

        // Drop-in conflict detection + foreign purge mirroring
        $this->cache_integration->init();

        // Bloat Remover & Relational Auto-Purge
        $this->bloat_remover->init();
        $this->auto_purge->init();

        // Async optimization pipeline: dispatch to edge, poll, download critical CSS
        add_action('wp_instant_async_optimize', [$this, 'run_async_optimize'], 10, 2);

        // Config sync: after local settings saves, mirror the config to the
        // cloud dashboard (verify_connection) instead of waiting a day for
        // the heartbeat.
        add_action('wp_instant_config_sync', [$this, 'run_config_sync']);

        // Self-update channel: probe the control plane for a newer published
        // zip and surface the one-click update row in WP-Admin.
        $this->updater->register();
        add_action('wp_instant_updater_check', [$this->updater, 'refresh_version_cache']);
        if (!wp_next_scheduled('wp_instant_updater_check')) {
            wp_schedule_event(time() + 10 * MINUTE_IN_SECONDS, 'daily', 'wp_instant_updater_check');
        }

        // Daily health heartbeat to the SaaS control plane
        add_action('wp_instant_health_heartbeat', [$this, 'run_health_heartbeat']);
        if (!wp_next_scheduled('wp_instant_health_heartbeat')) {
            wp_schedule_event(time() + HOUR_IN_SECONDS, 'daily', 'wp_instant_health_heartbeat');
        }

        // Hourly RUM heartbeat: push aggregated telemetry + evaluate the
        // auto-degrade safety net on live error rates.
        add_action('wp_instant_rum_heartbeat', [$this, 'run_rum_heartbeat']);
        if (!wp_next_scheduled('wp_instant_rum_heartbeat')) {
            wp_schedule_event(time() + HOUR_IN_SECONDS, 'hourly', 'wp_instant_rum_heartbeat');
        }

        // Frequent media derivative generation (R2 offload queue: webp
        // derivatives + edge uploads; nothing runs when the queue is empty).
        // Newly enqueued items also kick a due-now run from enqueue(), so
        // derivatives normally land in R2 within seconds — this recurring
        // event is only the backstop for drained-failure leftovers.
        add_filter('cron_schedules', static function (array $schedules): array {
            if (!isset($schedules['wp_instant_5min'])) {
                $schedules['wp_instant_5min'] = [
                    'interval' => 5 * MINUTE_IN_SECONDS,
                    'display' => 'Every 5 Minutes (WP Instant)',
                ];
            }
            return $schedules;
        });
        add_action('wp_instant_media_offload', [MediaOffloader::class, 'process_queue']);
        if (!wp_next_scheduled('wp_instant_media_offload')) {
            wp_schedule_event(time() + 2 * MINUTE_IN_SECONDS, 'wp_instant_5min', 'wp_instant_media_offload');
        }

        // Google Fonts localization runs off the render path: the first
        // request schedules this event and keeps the original Google link
        // until the localized package exists.
        add_action('wp_instant_localize_font', [FontOptimizer::class, 'localize_scheduled']);

        // Edge push callback (HMAC-verified REST route)
        OptimizeCallback::register_routes();

        // RUM telemetry endpoint (beacon receiver)
        Telemetry::register_routes();

        // Auto-degrade notices + dismiss handler
        add_action('admin_notices', [AutoDegrade::class, 'admin_notice']);
        AutoDegrade::register_ajax();

        // Initialize Dynamic Nonce & Cart Micro-Hydration
        $this->nonce_refresher->init();
        $this->cart_fragment->init();

        // Check Theme & Plugin Compatibility presets
        $this->preset_engine->apply_auto_presets();

        // Handle 1-Click Handshake Return (deferred to admin_init:
        // add_settings_error() is only loaded once wp-admin includes load).
        add_action('admin_init', [Handshake::class, 'handle_return']);

        // Initialize Admin UI
        if (is_admin()) {
            \WPInstant\AdminPage::get_instance()->init($this->config, $this->api_client, $this->cache_manager);
            $this->health_check->maybe_run();
        } elseif (is_user_logged_in() && current_user_can('manage_options')) {
            // Admin-bar Purge/Warm links target front-end URLs — register
            // the handler here or they are dead clicks outside wp-admin.
            \WPInstant\AdminPage::get_instance()->register_frontend_bar_hooks();
        }

        // Initialize Frontend Output Buffering for Cache & DOM Transformation
        if (!is_admin() && !wp_doing_ajax() && !wp_doing_cron()) {
            add_action('template_redirect', [$this, 'start_output_buffer'], -999999);
        }
    }

    /**
     * True for core REST (/wp-json/wp/v2/…) and AJAX/cron requests, where
     * core's nonce TTL must stay untouched. Detectable at plugins_loaded
     * time via the request URI (REST_REQUEST constant isn't defined yet).
     */
    private function is_core_rest_or_ajax(): bool {
        if (wp_doing_ajax() || wp_doing_cron()) {
            return true;
        }

        $route = '';
        $path = (string) (parse_url((string) ($_SERVER['REQUEST_URI'] ?? ''), PHP_URL_PATH) ?: '');
        $rest_prefix = function_exists('rest_get_url_prefix') ? rest_get_url_prefix() : 'wp-json';
        if (preg_match('#/' . preg_quote($rest_prefix, '#') . '(/[^?]*)#i', $path, $m)) {
            $route = $m[1];
        } elseif (isset($_GET['rest_route'])) {
            $route = (string) wp_unslash($_GET['rest_route']);
        }

        if ($route === '') {
            return false;
        }

        // Our own namespace mints nonces for frontend verification — it
        // needs the SAME extended TTL as the front end, not core's.
        return !str_starts_with(strtolower($route), '/wp-instant/');
    }

    public function start_output_buffer(): void {
        // Edge extractor bypass: serve the RAW origin page. Circular
        // extraction (parsing our own optimized output) was the root cause
        // of critical CSS missing JS-rendered elements and their
        // ::before/::after rules, and of skewed LCP measurements.
        if (isset($_GET['wp_instant_extract'])) {
            return;
        }

        $preview = false;

        // Preview flag: an admin carrying ?wpins_preview=1 always sees (and
        // verifies) the optimized page — mandatory in Test Mode, and the
        // verification tool in Live mode (logged-in requests otherwise
        // bypass the pipeline entirely, which made features like per-page
        // asset exclusion look "broken" to the admin testing them).
        if (current_user_can('manage_options') && isset($_GET['wpins_preview'])) {
            $preview = true;
        } elseif (($this->config->get('deployment.status', 'live')) === 'test') {
            // Test Mode without the flag: visitors get the untouched origin.
            return;
        }

        if (!$preview && !CacheRules::should_cache_request($this->config)) {
            return;
        }

        // The beacon must observe real traffic: live mode always, preview so
        // admins can check console health before deploying.
        $this->dom_engine->enable_rum($preview);

        if ($preview && !headers_sent()) {
            header('X-WP-Instant-Preview: 1');
            // Preview output is admin-only and must never land in an edge
            // cache between checks.
            header('Cache-Control: no-store');
        }
        // NOTE: no public Cache-Control here. Later hooks (redirects,
        // membership/cart plugins, DONOTCACHEPAGE) can still change the
        // response after template_redirect; cacheability is decided at
        // buffer flush via response_allows_cache().

        ob_start([$this, 'process_output_buffer']);
    }

    public function process_output_buffer(string $buffer): string {
        // Airlift-style response gate: only ever transform successful,
        // non-trivial HTML documents. Error pages/redirects/fragments pass
        // through untouched.
        if (
            strlen($buffer) <= 255 ||
            http_response_code() !== 200 ||
            stripos($buffer, '<html') === false
        ) {
            return $buffer;
        }

        try {
            // Transform DOM (Inject Critical CSS, Delay Scripts, Preload LCP, Inject Nonce Markers)
            $transformed = $this->dom_engine->transform($buffer);

            // Preview requests are never written to the static page cache.
            $is_preview = $this->is_preview_request();

            if (
                !$is_preview &&
                $this->config->get('caching.enabled', true) &&
                $this->response_allows_cache($transformed)
            ) {
                $this->cache_manager->write_cache($transformed);
                if (!headers_sent()) {
                    // Edge-cacheable HTML: fresh renders carry the SAME cache
                    // headers the advanced-cache drop-in sends on HITs, so any
                    // CDN/proxy in front of the origin can cache uniformly.
                    header('Cache-Control: public, max-age=3600, stale-while-revalidate=86400');
                    // Cache-state marker: the drop-in emits HIT/STALE; without a
                    // MISS marker here, fresh renders were indistinguishable from
                    // "plugin not serving at all" in response dumps.
                    header('X-WP-Instant-Cache: MISS');
                    // Transformation changed the bytes: a pre-set Content-Length
                    // is now stale and would truncate or pad the response.
                    header_remove('Content-Length');
                }
            }

            if ($is_preview) {
                $badge = '<div style="position:fixed;bottom:16px;right:16px;z-index:99999;background:#111;color:#fff;'
                    . 'padding:8px 14px;border-radius:8px;font:600 12px system-ui,sans-serif;box-shadow:0 2px 8px rgba(0,0,0,.3)">'
                    . '&#9889; WP Instant Test Preview v' . WP_INSTANT_VERSION . '</div>';
                if (stripos($transformed, '</body>') !== false) {
                    $transformed = str_ireplace('</body>', $badge . '</body>', $transformed);
                }
            }

            return $transformed;
        } catch (\Throwable) {
            // A host or another plugin can promote PHP warnings to exceptions.
            // Optimization is best-effort: fail open to the untouched origin
            // page instead of turning a cache race into a visitor-facing 500.
            return $buffer;
        }
    }

    private function is_preview_request(): bool {
        // Any admin carrying the preview flag (Test or Live mode): preview
        // output is never written to the static page cache.
        return current_user_can('manage_options') && isset($_GET['wpins_preview']);
    }

    /**
     * Final-response cache eligibility, evaluated at buffer flush — AFTER
     * every late hook (redirects, cookies, cache-policy headers) has run.
     * Anything a shared cache must not store stays out of the page cache
     * and keeps its original (non-public) cache headers.
     */
    private function response_allows_cache(string $buffer): bool {
        if (defined('DONOTCACHEPAGE') && DONOTCACHEPAGE) {
            return false;
        }
        if (http_response_code() !== 200 || stripos($buffer, '<html') === false) {
            return false;
        }
        foreach (headers_list() as $header) {
            $lower = strtolower($header);
            if (strpos($lower, 'set-cookie:') === 0) {
                return false;
            }
            if (strpos($lower, 'cache-control:') === 0) {
                foreach (['private', 'no-store', 'no-cache'] as $flag) {
                    if (strpos($lower, $flag) !== false) {
                        return false;
                    }
                }
            }
            if (strpos($lower, 'content-type:') === 0 && strpos($lower, 'text/html') === false) {
                return false;
            }
        }
        return true;
    }

    /**
     * Cron handler for 'wp_instant_async_optimize'.
     * Lifecycle: dispatch job(s) -> poll every 60s -> download CSS per viewport
     * -> write local cache -> purge page cache. Reschedules itself until done.
     *
     * Args are positional: associative arrays become PHP 8 named arguments
     * under WP-Cron (do_action_ref_array) and fatal with "Unknown named
     * parameter". Param names double as back-compat named args for any
     * legacy ['url'=>…,'attempt'=>…] events already in the cron option.
     */
    public function run_async_optimize(string $url = '', int $attempt = 0): void {

        if (empty($url) || !$this->config->is_connected()) {
            return;
        }

        $transient_key = 'wpins_jobs_' . md5($url);
        $jobs = get_transient($transient_key);

        // Phase 1: dispatch the extraction job(s).
        if (empty($jobs)) {
            $dispatch = $this->api_client->dispatch_optimization($url, ['mobile', 'desktop'], $this->compute_template_hash($url));
            $created = $dispatch['data']['jobs'] ?? null;

            if (empty($created)) {
                // Let the 10-minute throttle transient retry later.
                return;
            }

            $jobs = array_map(static fn(array $j): array => ['id' => $j['jobId'], 'viewport' => $j['viewport']], $created);
            set_transient($transient_key, $jobs, 30 * MINUTE_IN_SECONDS);
            wp_schedule_single_event(time() + 60, 'wp_instant_async_optimize', [$url, 1]);
            return;
        }

        // Phase 2: poll each job; download CSS as jobs complete.
        foreach ($jobs as $i => $job) {
            $status = $this->api_client->get_job_status($job['id']);
            $state = $status['data']['status'] ?? null;

            if ($state === 'completed') {
                // Push-mode parity: record the edge-verified LCP image so the
                // MediaOptimizer can preload CSS-background LCP candidates.
                $lcp_url = $status['data']['lcpImageUrl'] ?? null;
                if (!empty($lcp_url)) {
                    MediaOptimizer::store_lcp_image($url, $job['viewport'], (string) $lcp_url);
                }

                $css = $this->api_client->download_critical_css($url, $job['viewport']);
                if (!empty($css)) {
                    CriticalCssTransformer::write_cache_for_url($url, $job['viewport'], $css);
                }
                unset($jobs[$i]);
            } elseif ($state === 'failed') {
                unset($jobs[$i]);
            }
        }

        if (empty($jobs)) {
            delete_transient($transient_key);
            // Fresh HTML with inlined critical CSS on next request.
            CacheManager::purge_url($url);
            CacheIntegration::purge_foreign_caches('url', $url);
            return;
        }

        set_transient($transient_key, array_values($jobs), 30 * MINUTE_IN_SECONDS);

        // Keep polling (cap ~30 attempts / 30 min).
        if ($attempt < 30) {
            wp_schedule_single_event(time() + 60, 'wp_instant_async_optimize', [$url, $attempt + 1]);
        } else {
            delete_transient($transient_key);
        }
    }

    /** Cron: run the health check and push results to the SaaS dashboard. */
    public function run_health_heartbeat(): void {
        $this->health_check->run();
        $this->health_check->push_to_edge();
        $this->self_heal_purge();

        // DISABLE_WP_CRON fallback: the daily heartbeat also services the
        // RUM pipeline (hourly cron may never fire on some hosts).
        Telemetry::push_to_edge($this->api_client);
        AutoDegrade::evaluate($this->config);
    }

    /**
     * Template fingerprint for the edge's structure-hash dedup: hash the RAW
     * origin HTML (?wp_instant_extract=1 bypasses both the drop-in and the
     * DOM engine, matching what the extractor sees). Pages sharing a template
     * then complete from the edge's KV cache instead of paying a Chromium
     * job. Best-effort: null just means the dispatch runs uncached.
     */
    private function compute_template_hash(string $url): ?string {
        $loopback = wp_remote_get(add_query_arg('wp_instant_extract', '1', $url), [
            'timeout' => 8,
            'redirection' => 2,
        ]);
        if (is_wp_error($loopback) || wp_remote_retrieve_response_code($loopback) !== 200) {
            return null;
        }
        $html = (string) wp_remote_retrieve_body($loopback);
        if (strlen($html) < 512 || stripos($html, '</head>') === false) {
            return null;
        }
        return DomEngine::compute_structure_hash($html);
    }

    /**
     * Self-healing purge: when the daily health check finds the served
     * homepage missing/stale (a host cache like LiteSpeed pinned
     * pre-optimization HTML — PHP never runs, so nothing else can fix it),
     * flush our page cache AND the host's. Throttled so a persistent
     * mismatch can't purge-loop all day.
     */
    private function self_heal_purge(): void {
        if ($this->config->get('deployment.status', 'live') !== 'live') {
            return;
        }
        $health = get_option('wp_instant_health');
        if (!is_array($health) || empty($health['checks'])) {
            return;
        }
        foreach ((array) $health['checks'] as $check) {
            if (($check['key'] ?? '') === 'served_html_current' && ($check['status'] ?? '') !== 'ok') {
                if (get_transient('wpins_selfheal_purge')) {
                    return; // already tried within the throttle window
                }
                set_transient('wpins_selfheal_purge', 1, 6 * HOUR_IN_SECONDS);
                CacheManager::purge_all_static();
                CacheIntegration::purge_foreign_caches('all');
                return;
            }
        }
    }

    /**
     * Cron: mirror the current config to the cloud dashboard. Scheduled
     * after local settings-page saves so the SaaS UI reflects plugin-side
     * edits within seconds instead of at the next daily heartbeat.
     */
    public function run_config_sync(): void {
        if (!$this->config->is_connected()) {
            return;
        }
        $result = $this->api_client->verify_connection();
        if (!empty($result['success'])) {
            update_option('wp_instant_config_synced_at', time());
        }
    }

    /** Cron: push aggregated RUM + evaluate auto-degrade (hourly). */
    public function run_rum_heartbeat(): void {
        Telemetry::push_to_edge($this->api_client);
        AutoDegrade::evaluate($this->config);
    }

    public static function activate(): void {
        // Create cache folders (pages separated from artifacts)
        foreach ([WP_INSTANT_CACHE_DIR, WP_INSTANT_PAGES_DIR] as $dir) {
            if (!file_exists($dir)) {
                wp_mkdir_p($dir);
            }
        }

        // Install advanced-cache.php drop-in — only when the slot is free
        // (never clobber LiteSpeed / WP Rocket / host-level drop-ins).
        CacheIntegration::install_dropin();

        // Install .htaccess delivery rules (immutable cache TTLs +
        // precompressed .br/.gz serving) with loopback verification.
        Htaccess_Manager::install();

        // Stale host-cache entries from before activation must not survive.
        CacheIntegration::purge_foreign_caches('all');

        // Land the user on the Connect page after activation (Dashboard
        // instead when a connection already exists).
        update_option(AdminPage::ACTIVATION_REDIRECT_OPTION, true);
    }

    public static function deactivate(): void {
        // Remove OUR drop-in only; a foreign one is left untouched.
        CacheIntegration::remove_dropin();

        // Strip .htaccess rules + delete the pre-install backup.
        Htaccess_Manager::remove();

        // Clear all cached pages
        CacheManager::purge_all_static();

        // Host caches may still hold OUR transformed HTML (localized font
        // links, combined bundles) — force a fresh unoptimized render.
        CacheIntegration::purge_foreign_caches('all');

        // Unschedule heartbeats and background optimization tasks
        foreach (['wp_instant_health_heartbeat', 'wp_instant_rum_heartbeat', 'wp_instant_media_offload', 'wp_instant_async_optimize', 'wp_instant_config_sync', 'wp_instant_localize_font', 'wp_instant_updater_check'] as $hook) {
            $timestamp = wp_next_scheduled($hook);
            while ($timestamp) {
                wp_unschedule_event($timestamp, $hook);
                $timestamp = wp_next_scheduled($hook);
            }
        }
    }
}
