// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: "production";
	SAAS_APP_URL: "https://app.turbopress.io";
	ASSETS_BUCKET: R2Bucket;
	DB: D1Database;
	OPTIMIZATION_QUEUE: Queue;
	BROWSER: Fetcher;
}
